server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # APK downloads
  location ~* \.apk$ {
    default_type application/vnd.android.package-archive;
    add_header Content-Disposition 'attachment';
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
